### ISSUE TITLE
Core clock and peripheral clock 

### ISSUE THREAD

**Issue by jnorris1** [RISCV-on-Microsemi-FPGA/M2GL025-Creative-Board#11]
In the software for Systick_Blinky, there's a define for RTC_PRESCALE (riscv_hal.c). Is this value used
for 'm' in deriving (scaling?) the peripheral clock (clock) from the core clock (core_clock)?

**Comment by AntonKrug** [comment]
Not sure if I understand your question properly, so please rephrase your question if the following will not answer it:

The **RTC_PRESCALE** is **not driving** value in the peripheral/core clock. Changing this will not change the clocks relation, only will make the software not behave as you expect.  But it needs to reflect the ratio between the core clock and the mtime counter clock. 

From the RISCV's privileged spec: 

> Platforms provide a real-time counter, exposed as a memory-mapped machine-mode register, mtime.
> mtime must run at a constant frequency, and the platform must provide a mechanism for determining
> the timebase of mtime.

In this implementation, the ratio of mtime and cpu clock is 100.  This value should be changed if the hardware changed and has other ratio, but changing it will not change the hardware itself.

When you enable the systicks, the **RTC_PRESCALE** is dividing the **SYS_CLK_FREQ** (from **hw_platform.h** which has to be updated by hand to match clock of your current HW design) to calculate how many steps of mtime have to happen between the interupts.

**Comment by AntonKrug** [comment]
Can you confirm if the issue got solved or not? If you do not respond it may cause this issue to get closed automatically.
